npmRegistryServer: "https://registry.npmjs.org"
npmAlwaysAuth: false
networkTimeout: 100000

npmScopes:
  emotion:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAlwaysAuth: false
  mui:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAlwaysAuth: false
  babel:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAlwaysAuth: false 