[build]
  command = "corepack enable && corepack prepare yarn@1.22.19 --activate && yarn config set registry https://registry.yarnpkg.com && yarn config set always-auth false && yarn config set strict-ssl false && yarn netlify:build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.19"
  CI = "true"
  NODE_ENV = "production"
  USE_YARN = "true"
  YARN_FLAGS = "--frozen-lockfile --network-timeout 600000 --no-optional --non-interactive --no-progress"
  
  # Registry settings
  YARN_REGISTRY = "https://registry.yarnpkg.com"
  
  # Authentication settings
  YARN_AUTH_TOKEN = ""
  
  # SSL settings
  YARN_STRICT_SSL = "false"
  
  # Performance settings
  YARN_NETWORK_TIMEOUT = "600000"
  YARN_ENABLE_GLOBAL_CACHE = "true"
  YARN_ENABLE_MIRROR = "true"
  YARN_ENABLE_IMMUTABLE_CACHE = "true"
  
  # Dependency settings
  YARN_IGNORE_ENGINES = "true"
  YARN_IGNORE_OPTIONAL = "true"
  YARN_IGNORE_SCRIPTS = "true"
  YARN_NO_PROGRESS = "true"
  YARN_SILENT = "true"
  YARN_PRODUCTION = "true"
  YARN_PURE_LOCKFILE = "true"
  YARN_PREFER_OFFLINE = "true"
  YARN_SKIP_INTEGRITY_CHECK = "true"
  YARN_NON_INTERACTIVE = "true"
  YARN_DISABLE_SELF_UPDATE_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"