[build]
  command = "npm config set registry https://registry.npmjs.org/ && npm config set always-auth false && yarn config set registry https://registry.yarnpkg.com && yarn install --frozen-lockfile --network-timeout 600000 && yarn build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.19"
  CI = "true"
  NODE_ENV = "production"
  YARN_FLAGS = "--network-timeout 600000 --no-optional"
  USE_YARN = "true"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
  NPM_CONFIG_ALWAYS_AUTH = "false"
  NPM_TOKEN = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"