[build]
  command = "yarn install --frozen-lockfile && yarn build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.19"
  CI = "true"
  NODE_ENV = "production"
  USE_YARN = "true"
  YARN_FLAGS = "--frozen-lockfile --network-timeout 600000 --no-optional"
  
  # Registry settings
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
  YARN_REGISTRY = "https://registry.yarnpkg.com"
  
  # Authentication settings
  NPM_CONFIG_ALWAYS_AUTH = "false"
  NPM_TOKEN = ""
  YARN_AUTH_TOKEN = ""
  
  # SSL settings
  NPM_CONFIG_STRICT_SSL = "false"
  YARN_STRICT_SSL = "false"
  
  # Performance settings
  YARN_NETWORK_TIMEOUT = "600000"
  YARN_ENABLE_GLOBAL_CACHE = "true"
  YARN_ENABLE_MIRROR = "true"
  YARN_ENABLE_IMMUTABLE_CACHE = "true"
  
  # Dependency settings
  YARN_IGNORE_ENGINES = "true"
  YARN_IGNORE_OPTIONAL = "true"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_ENGINE_STRICT = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"