[build]
  command = "corepack enable && yarn install --frozen-lockfile && yarn build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.19"
  CI = "true"
  NODE_ENV = "production"
  NPM_FLAGS = "--no-optional"
  YARN_FLAGS = "--no-optional --frozen-lockfile --network-timeout 600000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"