[build]
  command = "npm config set registry https://registry.npmjs.org/ && npm config set always-auth false && npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
  NPM_CONFIG_ALWAYS_AUTH = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 