[build]
  command = "yarn install && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.0"
  YARN_VERSION = "1.22.22"
  YARN_FLAGS = "--no-lockfile --non-interactive"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 