[build]
  command = "yarn config set registry https://registry.yarnpkg.com && yarn config set always-auth false && yarn config set strict-ssl false && yarn install --frozen-lockfile --network-timeout 600000 && yarn build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.19"
  CI = "true"
  NODE_ENV = "production"
  YARN_FLAGS = "--network-timeout 600000 --no-optional --frozen-lockfile"
  USE_YARN = "true"
  YARN_REGISTRY = "https://registry.yarnpkg.com"
  YARN_ENABLE_GLOBAL_CACHE = "true"
  YARN_ENABLE_MIRROR = "true"
  YARN_ENABLE_IMMUTABLE_CACHE = "true"
  YARN_ENABLE_TELEMETRY = "false"
  YARN_IGNORE_ENGINES = "true"
  YARN_IGNORE_OPTIONAL = "true"
  YARN_STRICT_SSL = "false"
  YARN_NETWORK_TIMEOUT = "600000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"