[build]
  command = "corepack enable && corepack prepare yarn@1.22.19 --activate && yarn install --frozen-lockfile --network-timeout 600000 && yarn build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.19"
  CI = "true"
  NODE_ENV = "production"
  YARN_FLAGS = "--network-timeout 600000 --no-optional"
  USE_YARN = "true"
  YARN_REGISTRY = "https://registry.yarnpkg.com"
  YARN_ENABLE_GLOBAL_CACHE = "true"
  YARN_ENABLE_MIRROR = "true"
  YARN_ENABLE_IMMUTABLE_CACHE = "true"
  NPM_CONFIG_ENGINE_STRICT = "true"
  SKIP_NPM = "true"
  DISABLE_NPM = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"