services:
  - type: web
    name: resume-builder
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false 